trigger:
  - development
  - uat
  - production

pool:
  name: LinuxAgentPool
  demands:
    - JDK -equals 17
    - Terraform -equals Yes
    - Agent.Name -equals ProdADO

variables:
  global_version: "1.0.0"
  global_email: "sonalkumar2790@gmail.com"
  # azure_dev_sub: "9ce91e05-4b9e-4a42-95c1-4385c54920c6"
  # azure_prod_sub: "298f2c19-014b-4195-b821-e3d8fc25c2a8"
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/development')]
  isProd: $[eq(variables['Build.SourceBranch'], 'refs/heads/production')]

stages:
  - stage: CheckingTheAgent
    condition: and(succeeded(), eq(variables.isDev, true))
    pool:
      name: LinuxAgentPool
      demands:
        - Terraform -equals Yes
    variables:
      stage_version: "2.0.0"
      stage_email: "sonalkumar2790@gmail.com"
    jobs:
      - job: CheckingTerraformAndPacker
        variables:
          job_version: "3.0.0"
          job_email: "sonalkumar2790@gmail.com"
        timeoutInMinutes: 5
        steps:
          - script: echo $(Build.BuildId)
            displayName: "Display The Build-ID"
          - script: terraform version && packer version
            displayName: "Display Terraform & Packer Version"
          - script: docker version && docker ps && docker images && docker ps -a
            displayName: "Display Docker Version"
          - script: pwd && ls -al
            displayName: "List Folder & Files"

  - stage: SASTWithSonarQube
    condition: and(succeeded(), eq(variables.isDev, true))
    pool:
      name: LinuxAgentPool
      demands:
        - JDK -equals 17
    jobs:
      - job: RunningSASTWithSonarqube
        timeoutInMinutes: 10
        steps:
          #SonarQube User Token need to be generated and used in the ServiceConnection.
          #Also change name of the project and artifactId(line 6 & 14) to ado-spring-boot-app-dev in POM.
          #No need to create a project in sonarqube as its created automatically.
          - task: SonarQubePrepare@7
            inputs:
              SonarQube: "SonarTestToken"
              scannerMode: "Other"
              projectVersion: "$(Build.BuildId)"
            displayName: "Preparing SonarQube Config"
          - task: Maven@4
            inputs:
              mavenPomFile: "pom.xml"
              publishJUnitResults: false
              javaHomeOption: "JDKVersion"
              mavenVersionOption: "Default"
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: "latest"
              options: "-DskipTests"
            displayName: "Running SonarQube Maven Analysis"
          - task: SonarQubePublish@7
            inputs:
              SonarQube: "SonarTestToken"
              pollingTimeoutSec: "300"  
            displayName: "SAST Job Fail or Pass"

  - stage: BuildAndPushToAzureArtifacts
    condition: and(succeeded(), eq(variables.isDev, true))
    #condition: always()
    pool:
      name: LinuxAgentPool
      demands:
        - Terraform -equals Yes
    jobs:
      - job: BuildingJavaCodeJob
        timeoutInMinutes: 15
        steps:
          - script: ls -al && pwd && rm -rf /home/adminsonal/.m2/settings.xml
            displayName: "List Files & Current Working Directory"
          - task: MavenAuthenticate@0
            inputs:
              artifactsFeeds: 'PROD-AD'  #feed name
              mavenServiceConnections: '' 
          - script: mvn versions:set -DnewVersion=Dev-2.0.$(Build.BuildId)
            displayName: "Set Maven Build Version"
          - script: mvn clean package install && ls -al
            displayName: "Run the maven build and install"
          - script: mvn deploy && ls -al
            displayName: "Run the maven deploy"
            continueOnError: true
            # env:  
            #   AZURE_DEVOPS_PAT: $(System.AccessToken)
          - script: ls -al && cp /home/adminsonal/myagent/_work/1/s/target/spring-petclinic-Dev-2.0.$(Build.BuildId).jar ROOT$(Build.BuildId).jar && ls -al
            displayName: "List Files & Rename ROOT.jar"
          - script: rm -rf /artifacts/*.jar && cp ROOT$(Build.BuildId).jar /artifacts && ls -al /artifacts
            displayName: "Copy Artifact To Folder"
          - task: CopyFiles@2
            inputs:
              Contents: "ROOT$(Build.BuildId).jar"
              TargetFolder: "$(Build.ArtifactStagingDirectory)"
              OverWrite: true
            displayName: "Copying JAR file to ArtifactStagingDirector"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "ROOT$(Build.BuildId).jar"
              publishLocation: "Container"
            displayName: "Publishing JAR Artifact."
  - stage: CopyingArtifactsToAzureAndAws
    condition: and(succeeded(), eq(variables.isDev, true))
    jobs:
      - job: CopyFilesToAzureBlob
        timeoutInMinutes: 5
        steps:
          - checkout: none
          - task: AzureCLI@2
            inputs:
              azureSubscription: "sonalsecops-subscription"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az storage blob upload-batch --account-name sonalsecopsprod  --account-key $(STORAGE_ACCOUNT_KEY) --destination artifacts --source /artifacts/
            displayName: "Azure Upload artifacts to Azure Blob"
            continueOnError: true
      - job: CopyFilesToAWSS3Bucket
        dependsOn: CopyFilesToAzureBlob
        condition: always() # succeededOrFailed() or always() or failed() or succeeded()-default
        timeoutInMinutes: 5
        steps:
          - checkout: none
          - task: S3Upload@1
            inputs:
              awsCredentials: "sonalsecops-s3"
              regionName: "us-east-1"
              bucketName: "sonalsecopss3uploadprodartifacts"
              sourceFolder: "/artifacts/"
              globExpressions: "ROOT$(Build.BuildId).jar"
            displayName: "AWS Upload artifacts to AWS S3 Bucket"
            continueOnError: true
  - stage: DockerBuildAndTrivyScan
    condition: and(succeeded(), eq(variables.isDev, true))
    pool:
      name: LinuxAgentPool
    jobs:
      - job: BuildingContainerImageAndSecurityScanning
        timeoutInMinutes: 10
        steps:
          - checkout: none
          - script: docker build -t sonalkumarsingh/myjavaapp:$(Build.BuildId) .
            displayName: "Create Docker Image"
          #- script: trivy image --severity HIGH,CRITICAL --format template --template "@template/junit.tpl" -o junit-report-high-crit.xml sonalkumarsingh/myapp:$(Build.BuildId)
          - script: |
              trivy image --exit-code 0 --severity LOW,MEDIUM --format template --template "@template/junit.tpl" -o junit-report-low-med.xml sonalkumarsingh/myjavaapp:$(Build.BuildId)
              trivy image --exit-code 0 --severity HIGH,CRITICAL --format template --template "@template/junit.tpl" -o junit-report-high-crit.xml sonalkumarsingh/myjavaapp:$(Build.BuildId)
            displayName: "Scan Image and Create Report"
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "**/junit-report-low-med.xml"
              mergeTestResults: true
              failTaskOnFailedTests: false
              testRunTitle: "Trivy - Low and Medium Vulnerabilities"
            displayName: "Trivy - Low and Medium Vulnerabilities"
            condition: "always()"
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "**/junit-report-high-crit.xml"
              mergeTestResults: true
              failTaskOnFailedTests: false
              testRunTitle: "Trivy - High and Critical Vulnerabilities"
            displayName: "Trivy - High and Critical Vulnerabilities"
            condition: "always()"
  - stage: BuildDockerImagePushToAzureACRAndDockerHub
    condition: and(succeeded(), eq(variables.isDev, true))
    jobs:
      - job: PushToAzureACR
        #dependsOn: DockerBuildAndTrivyScan
        condition: always() # succeededOrFailed() or always() or failed()
        timeoutInMinutes: 5
        steps:
          - checkout: none
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                docker login -u devsopsacrtest -p $(acrpassword) devsopsacrtest.azurecr.io
                docker tag sonalkumarsingh/myjavaapp:$(Build.BuildId) devsopsacrtest.azurecr.io/devsecopsacrtest:$(Build.BuildId)
                docker push devsopsacrtest.azurecr.io/devsecopsacrtest:$(Build.BuildId)
            displayName: "Creating & Pushing Docker Image To Azure ACR"
      - job: PushToDockerHub
        dependsOn: PushToAzureACR
        condition: always() # succeededOrFailed() or always() or failed()
        timeoutInMinutes: 5
        steps:
          - checkout: none
          - task: Docker@2
            inputs:
              containerRegistry: "devops-dockerhub-connection"
              command: "login"
            displayName: "Login To Docker Hub"
          - task: Bash@3
            inputs:
              targetType: "inline"
              script: |
                docker tag sonalkumarsingh/myjavaapp:$(Build.BuildId) sonalkumarsingh/devsecopsado:$(Build.BuildId)
                docker push sonalkumarsingh/devsecopsado:$(Build.BuildId)
            displayName: "Pushing Docker Image To Docker Hub"
  - stage: DeployDockerImageToAzureACI
    condition: and(succeeded(), eq(variables.isDev, true))
    pool:
      name: LinuxAgentPool
      demands:
        - JDK -equals 17
    jobs:
      - job: DeployAzureACI
        timeoutInMinutes: 10
        steps:
          - checkout: none
          - task: AzureCLI@2
            inputs:
              azureSubscription: "sonalsecops-subscription"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: "az container create -g Prod_ADO-1 --name devsecopsado$(Build.BuildId) --image devsopsacrtest.azurecr.io/devsecopsacrtest:$(Build.BuildId) --cpu 2 --memory 4 --ports 8080 --dns-name-label devsecopsado$(Build.BuildId) --registry-username devsopsacrtest --registry-password $(acrpassword) --location eastus --os-type Linux"
              #inlineScript: az group list
            displayName: "Deploy Docker Image to Azure Container Instances"
            continueOnError: true
  - stage: "DeployingToStagingEnvironment"
    dependsOn: BuildAndPushToAzureArtifacts
    condition: and(succeeded(), eq(variables.isDev, true))
    pool:
      name: LinuxAgentPool
    displayName: "Deploying To AWS Staging Environment"
    jobs:
      - deployment: "DeployJARtoStagingServer"
        environment:
          name: STAGING
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    PROC=$(ps -ef | grep -i jar | grep -v grep | awk '{print $2}')
                    if [ -n "$PROC" ]; then
                      echo "Stopping process with PID: $PROC"
                      sudo kill -9 $PROC || echo "Failed to stop process."
                    else
                      echo "No JAR process found. Nothing to stop."
                    fi
                    exit 0  # Force success status
                  displayName: "Stop Existing JAR File"

                - script: |
                    sudo java -jar /home/ubuntu/azagent/_work/1/ROOT$(Build.BuildId).jar/ROOT$(Build.BuildId).jar &
                    echo "Application started successfully."
                    exit 0  # Force success status
                  displayName: "Running The Jar File"

  - stage: ZAPOWASPTestingStagingEnvironment
    condition: and(succeeded(), eq(variables.isDev, true))
    jobs:
      - job: ZapTestingStaging
        timeoutInMinutes: 20
        steps:
          - checkout: none

          # Pull the OWASP ZAP image and run the baseline scan
          - script: |
              docker pull ghcr.io/zaproxy/zaproxy:stable
              docker run -u 0 -v $(Pipeline.Workspace)/owaspzap:/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://13.232.77.118:8080/ -J report.json -r report.html -I -i
            displayName: "DAST Staging Environment"
            continueOnError: true

          # Publish the ZAP test results
          - task: PublishTestResults@2
            displayName: "Publish Test Results For ZAP Testing"
            inputs:
              testResultsFormat: "NUnit"
              testResultsFiles: "$(Pipeline.Workspace)/owaspzap/report.html"

  - stage: "DeployingToProdEnvironment"
    dependsOn: BuildAndPushToAzureArtifacts
    condition: or(eq(variables.isProd, true), eq(variables.isDev, true)),
    #condition: and(succeeded('BuildingJavaCodeWithMavenCopyToJFrog'), eq(variables.isProd, true))
    pool:
      name: LinuxAgentPool
    displayName: "Deploying To AWS Prod Environment"
    jobs:
      - deployment: "DeployJARtoProdServer"
        environment:
          name: PROD
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    PROC=$(ps -ef | grep -i jar | grep -v grep | awk '{print $2}')
                    if [ -n "$PROC" ]; then
                      echo "Stopping process with PID: $PROC"
                      sudo kill -9 $PROC || echo "Failed to stop process."
                    else
                      echo "No JAR process found. Nothing to stop."
                    fi
                  displayName: "Stop Existing JAR File"
                  continueOnError: true

                - script: |
                    sudo java -jar /home/ubuntu/azagent/_work/1/ROOT$(Build.BuildId).jar/ROOT$(Build.BuildId).jar > /dev/null 2>&1 &
                    echo "Application started successfully."
                  displayName: "Running The Jar File"
                  continueOnError: true