trigger:
  - development
  - uat
  - production

pool:
  name: LinuxAgentPool
  demands:
    - JDK -equals 17
    - Terraform -equals Yes
    - Agent.Name -equals ProdADO

variables:
  global_version: "1.0.0"
  global_email: "sonalkumar2790@gmail.com"
  # azure_dev_sub: "9ce91e05-4b9e-4a42-95c1-4385c54920c6"
  # azure_prod_sub: "298f2c19-014b-4195-b821-e3d8fc25c2a8"
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/development')]
  isProd: $[eq(variables['Build.SourceBranch'], 'refs/heads/production')]

stages:
  - stage: CheckingTheAgent
    condition: and(succeeded(), eq(variables.isDev, true))
    pool:
      name: LinuxAgentPool
      demands:
        - Terraform -equals Yes
    variables:
      stage_version: "2.0.0"
      stage_email: "sonalkumar2790@gmail.com"
    jobs:
      - job: CheckingTerraformAndPacker
        variables:
          job_version: "3.0.0"
          job_email: "sonalkumar2790@gmail.com"
        timeoutInMinutes: 5
        steps:
          - script: echo $(Build.BuildId)
            displayName: "Display The Build-ID"
          - script: terraform version && packer version
            displayName: "Display Terraform & Packer Version"
          - script: docker version && docker ps && docker images && docker ps -a
            displayName: "Display Docker Version"
          - script: pwd && ls -al
            displayName: "List Folder & Files"

  - stage: SASTWithSonarQube
    condition: and(succeeded(), eq(variables.isDev, true))
    pool:
      name: LinuxAgentPool
      demands:
        - JDK -equals 17
    jobs:
      - job: RunningSASTWithSonarqube
        timeoutInMinutes: 10
        steps:
          #SonarQube User Token need to be generated and used in the ServiceConnection.
          #Also change name of the project and artifactId(line 6 & 14) to ado-spring-boot-app-dev in POM.
          #No need to create a project in sonarqube as its created automatically.
          - task: SonarQubePrepare@7
            inputs:
              SonarQube: "SonarTestToken"
              scannerMode: "Other"
              projectVersion: "$(Build.BuildId)"
            displayName: "Preparing SonarQube Config"
          - task: Maven@4
            inputs:
              mavenPomFile: "pom.xml"
              publishJUnitResults: false
              javaHomeOption: "JDKVersion"
              mavenVersionOption: "Default"
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: "latest"
              options: "-DskipTests"
            displayName: "Running SonarQube Maven Analysis"
          - task: SonarQubePublish@7
            inputs:
              SonarQube: "SonarTestToken"
              pollingTimeoutSec: "300"  
            displayName: "SAST Job Fail or Pass"